version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=graphql
    ports:
      - '4004:5432'
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - db
    command: bash -c "poetry run alembic upgrade head && poetry run python3 main.py"
  frontend:
    build: ./frontend/todolist
    environment:
      - PORT=3000
      - REACT_APP_GRAPHQL_BASE_URL=http://localhost:8000/graphql
    ports:
      - '3000:3000'    
